[project]
name = "ffg"
authors = []
description = ""
telemetry = false
requirements = []
cache_dir = "/home/runner/workspace/ffg/./.requirements"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.Cosmic-Investment-Orchestration]
path = "contracts/Cosmic-Investment-Orchestration.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
